Write-Host "--- Windows Monitor Agent Autostart Setup ---"
Write-Host "Due to issues with pm2 startup on Windows, it is recommended to use Windows Task Scheduler."
Write-Host ""
Write-Host "Step 1: Ensure pm2 is installed globally (npm install -g pm2)"
Write-Host "Step 2: Start the agent (pm2 start ecosystem.config.cjs)"
Write-Host "Step 3: Save pm2 list (pm2 save)"
Write-Host "Step 4: Create a Windows Task Scheduler task:"
Write-Host "  - Trigger: At startup"
Write-Host "  - Action: Start a program"
Write-Host "  - Program: pm2"
Write-Host "  - Arguments: resurrect"
Write-Host ""
Write-Host "Alternatively, you can use pm2-windows-service if supported by your Windows version."
